### ISSUE TITLE
herokuへデプロイしたい

### ISSUE THREAD

**Issue by sumikawa-40** [sumikawa-40/onigiri#39]
- 質問内容・実現したいこと

herokuへデプロイをしたいです。

- 現状発生している問題・エラーメッセージ

herokuへデプロイができていない状況です。
[![Image from Gyazo](https://i.gyazo.com/f1872bd3bf0b24cbd310dbd4d8b84e3c.png)](https://gyazo.com/f1872bd3bf0b24cbd310dbd4d8b84e3c)

- どの処理までうまく動いているのか

herokuへpushはできていると思われます。

```ruby
chinatsusumikawa@MacBook-Air onigiri % git push heroku main
Enumerating objects: 191, done.
Counting objects: 100% (191/191), done.
Delta compression using up to 8 threads
Compressing objects: 100% (165/165), done.
Writing objects: 100% (191/191), 41.53 KiB | 5.19 MiB/s, done.
Total 191 (delta 59), reused 3 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (59/59), done.

途中省略

remote:        Released v4
remote:        https://onigiri.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/onigiri.git
 * [new branch]      main -> main
```

- 該当のソースコード

config/database.yml

```ruby
# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: onigiri_development

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user running Rails.
  #username: onigiri

  # The password associated with the postgres role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: onigiri_test

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  url: <%= ENV['DATABASE_URL'] %>
```

herokuでのログを確認

**Application Logs**

```ruby
2023-06-13T11:25:42.973616+00:00 app[api]: Starting process with command `rails db:migrate` by user china.sumikawa@nifty.com
2023-06-13T11:25:46.686275+00:00 heroku[run.3185]: Awaiting client
2023-06-13T11:25:46.700273+00:00 heroku[run.3185]: Starting process with command `rails db:migrate`
2023-06-13T11:25:46.797474+00:00 heroku[run.3185]: State changed from starting to up
2023-06-13T11:25:51.423977+00:00 heroku[run.3185]: Process exited with status 1
2023-06-13T11:25:51.452538+00:00 heroku[run.3185]: State changed from up to complete
2023-06-13T11:26:02.789727+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=onigiri.herokuapp.com request_id=74dc6b95-d5f6-4331-be9e-1bf7c5dc6c8d fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:26:03.021850+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=onigiri.herokuapp.com request_id=b7d421f4-f78a-4a6c-b18f-78d94f559b8a fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:43:09.088632+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=onigiri.herokuapp.com request_id=5b80b734-1f60-4bce-871a-9e30c9794281 fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:43:09.341060+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=onigiri.herokuapp.com request_id=e7a58899-a25c-4f4c-b2ad-0191fcb46218 fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
```

ターミナルにて　heroku logsを実行

```ruby
chinatsusumikawa@MacBook-Air onigiri % heroku logs
2023-06-13T10:44:24.454359+00:00 app[web.1]: Exiting
2023-06-13T10:44:24.454491+00:00 app[web.1]: /app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract/connection_handler.rb:261:in `resolve_pool_config': database configuration does not specify adapter (ActiveRecord::AdapterNotSpecified)
2023-06-13T10:44:24.454492+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract/connection_handler.rb:129:in `establish_connection'
2023-06-13T10:44:24.454493+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_handling.rb:52:in `establish_connection'
2023-06-13T10:44:24.454493+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/railtie.rb:268:in `block (2 levels) in <class:Railtie>'
2023-06-13T10:44:24.454493+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5/lib/active_support/lazy_load_hooks.rb:95:in `class_eval'
2023-06-13T10:44:24.454493+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5/lib/active_support/lazy_load_hooks.rb:95:in `block in execute_hook'
2023-06-13T10:44:24.454494+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
2023-06-13T10:44:24.454494+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
2023-06-13T10:44:24.454494+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5/lib/active_support/lazy_load_hooks.rb:76:in `block in run_load_hooks'
2023-06-13T10:44:24.454495+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5/lib/active_support/lazy_load_hooks.rb:75:in `each'
2023-06-13T10:44:24.454495+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5/lib/active_support/lazy_load_hooks.rb:75:in `run_load_hooks'
2023-06-13T10:44:24.454495+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/base.rb:333:in `<module:ActiveRecord>'
2023-06-13T10:44:24.454495+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/base.rb:15:in `<main>'
2023-06-13T10:44:24.454496+00:00 app[web.1]: from <internal:/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-06-13T10:44:24.454496+00:00 app[web.1]: from <internal:/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-06-13T10:44:24.454496+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2023-06-13T10:44:24.454497+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'
2023-06-13T10:44:24.454497+00:00 app[web.1]: from /app/app/models/application_record.rb:1:in `<main>'
2023-06-13T10:44:24.454497+00:00 app[web.1]: from <internal:/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-06-13T10:44:24.454497+00:00 app[web.1]: from <internal:/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-06-13T10:44:24.454498+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2023-06-13T10:44:24.454498+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:30:in `require'
2023-06-13T10:44:24.454498+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
2023-06-13T10:44:24.454498+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:135:in `cget'
2023-06-13T10:44:24.454498+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
2023-06-13T10:44:24.454498+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
2023-06-13T10:44:24.454498+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:25:in `each'
2023-06-13T10:44:24.454499+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/helpers.rb:25:in `ls'
2023-06-13T10:44:24.454500+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
2023-06-13T10:44:24.454500+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
2023-06-13T10:44:24.454500+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:16:in `each'
2023-06-13T10:44:24.454500+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
2023-06-13T10:44:24.454501+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
2023-06-13T10:44:24.454501+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
2023-06-13T10:44:24.454503+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader.rb:329:in `block in eager_load_all'
2023-06-13T10:44:24.454504+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader.rb:327:in `each'
2023-06-13T10:44:24.454504+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/loader.rb:327:in `eager_load_all'
2023-06-13T10:44:24.454504+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
2023-06-13T10:44:24.454504+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5/lib/rails/initializable.rb:32:in `instance_exec'
2023-06-13T10:44:24.454504+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5/lib/rails/initializable.rb:32:in `run'
2023-06-13T10:44:24.454504+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5/lib/rails/initializable.rb:61:in `block in run_initializers'
2023-06-13T10:44:24.454504+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
2023-06-13T10:44:24.454505+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2023-06-13T10:44:24.454505+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
2023-06-13T10:44:24.454505+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
2023-06-13T10:44:24.454505+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
2023-06-13T10:44:24.454505+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
2023-06-13T10:44:24.454506+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
2023-06-13T10:44:24.454506+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
2023-06-13T10:44:24.454506+00:00 app[web.1]: from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
2023-06-13T10:44:24.454507+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5/lib/rails/initializable.rb:60:in `run_initializers'
2023-06-13T10:44:24.454507+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5/lib/rails/application.rb:372:in `initialize!'
2023-06-13T10:44:24.454507+00:00 app[web.1]: from /app/config/environment.rb:5:in `<main>'
2023-06-13T10:44:24.454507+00:00 app[web.1]: from config.ru:3:in `require_relative'
2023-06-13T10:44:24.454507+00:00 app[web.1]: from config.ru:3:in `block in <main>'
2023-06-13T10:44:24.454507+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `eval'
2023-06-13T10:44:24.454508+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:116:in `new_from_string'
2023-06-13T10:44:24.454508+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:105:in `load_file'
2023-06-13T10:44:24.454508+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/builder.rb:66:in `parse_file'
2023-06-13T10:44:24.454508+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:349:in `build_app_and_options_from_config'
2023-06-13T10:44:24.454508+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:249:in `app'
2023-06-13T10:44:24.454508+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:422:in `wrapped_app'
2023-06-13T10:44:24.454508+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:312:in `block in start'
2023-06-13T10:44:24.454508+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:379:in `handle_profiling'
2023-06-13T10:44:24.454508+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/server.rb:311:in `start'
2023-06-13T10:44:24.454509+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5/lib/rails/commands/server/server_command.rb:38:in `start'
2023-06-13T10:44:24.454509+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5/lib/rails/commands/server/server_command.rb:143:in `block in perform'
2023-06-13T10:44:24.454509+00:00 app[web.1]: from <internal:kernel>:90:in `tap'
2023-06-13T10:44:24.454509+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5/lib/rails/commands/server/server_command.rb:134:in `perform'
2023-06-13T10:44:24.454509+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
2023-06-13T10:44:24.454509+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
2023-06-13T10:44:24.454509+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
2023-06-13T10:44:24.454509+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5/lib/rails/command/base.rb:87:in `perform'
2023-06-13T10:44:24.454510+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5/lib/rails/command.rb:48:in `invoke'
2023-06-13T10:44:24.454510+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5/lib/rails/commands.rb:18:in `<main>'
2023-06-13T10:44:24.454510+00:00 app[web.1]: from <internal:/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-06-13T10:44:24.454510+00:00 app[web.1]: from <internal:/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2023-06-13T10:44:24.454510+00:00 app[web.1]: from /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2023-06-13T10:44:24.454512+00:00 app[web.1]: from bin/rails:4:in `<main>'
2023-06-13T10:44:24.572683+00:00 heroku[web.1]: Process exited with status 1
2023-06-13T10:44:24.600888+00:00 heroku[web.1]: State changed from starting to crashed
2023-06-13T10:50:24.898358+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=onigiri.herokuapp.com request_id=5cd4df7a-2139-4c1c-b52a-3c40de0441c0 fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T10:50:25.153873+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=onigiri.herokuapp.com request_id=866cd0da-af9a-4ab6-9934-7cfbd8901e9b fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T10:51:30.492642+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=onigiri.herokuapp.com request_id=4635687a-b64e-4f0c-8314-1d4580899b77 fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T10:51:30.743401+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=onigiri.herokuapp.com request_id=7796a6fd-6e2a-4efa-8d0e-940a9214364f fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:17:12.384359+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=onigiri.herokuapp.com request_id=5ece4001-b137-4d4a-9af8-7504485c356a fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:17:12.625606+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=onigiri.herokuapp.com request_id=d1c13144-a3de-44b3-8bee-802d04eb9b6b fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:25:17.637692+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=onigiri.herokuapp.com request_id=f2e19737-3982-4ac5-9dba-8e8ea010db95 fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:25:17.883246+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=onigiri.herokuapp.com request_id=2ac7b8e4-52b5-45ca-987c-0b9300966f12 fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:25:42.973616+00:00 app[api]: Starting process with command `rails db:migrate` by user china.sumikawa@nifty.com
2023-06-13T11:25:46.686275+00:00 heroku[run.3185]: Awaiting client
2023-06-13T11:25:46.700273+00:00 heroku[run.3185]: Starting process with command `rails db:migrate`
2023-06-13T11:25:46.797474+00:00 heroku[run.3185]: State changed from starting to up
2023-06-13T11:25:51.423977+00:00 heroku[run.3185]: Process exited with status 1
2023-06-13T11:25:51.452538+00:00 heroku[run.3185]: State changed from up to complete
2023-06-13T11:26:02.789727+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=onigiri.herokuapp.com request_id=74dc6b95-d5f6-4331-be9e-1bf7c5dc6c8d fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:26:03.021850+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=onigiri.herokuapp.com request_id=b7d421f4-f78a-4a6c-b18f-78d94f559b8a fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:43:09.088632+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=onigiri.herokuapp.com request_id=5b80b734-1f60-4bce-871a-9e30c9794281 fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:43:09.341060+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=onigiri.herokuapp.com request_id=e7a58899-a25c-4f4c-b2ad-0191fcb46218 fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https

```

- エラーから考えられる原因

config/database.yml の`production:　url: <%= ENV['DATABASE_URL'] %>`

の実装が違う、または　postgresqlの設定が違うのかもしれないと思いましたが、原因がはっきりとわかりません。

ローカルでは表示されています。
[![Image from Gyazo](https://i.gyazo.com/87398dcec0f0381553d171da02fab726.png)](https://gyazo.com/87398dcec0f0381553d171da02fab726)

- 試したこと

git push heroku mainを実行後

カリキュラム：インフラ入門：アプリケーションのデプロイ　に記載してある、`heroku open`

と`heroku run rails db:migrate`をしましたが、変わりませんでした。

**Comment by kenchasonakai** [comment]
herokuへのpush時に追加で打ったコマンドや追加で行った設定などがあれば共有をお願いします

また、ログの内容などで原因を検索しましたか？
検索して出てきた自分と近そうな原因などを共有していただいても良いでしょうか？

**Comment by sumikawa-40** [comment]
> herokuへのpush時に追加で打ったコマンド

 heroku updateを行いました。
```
chinatsusumikawa@MacBook-Air onigiri % heroku update
heroku: Updating CLI from 7.68.2 to 8.1.7-9f57985... done
heroku: Updating CLI... done
chinatsusumikawa@MacBook-Air onigiri % git push heroku main
Everything up-to-date
```

また、heroku open　と　heroku run rails db:migrateをしましたが、変わりませんでした。

> herokuへのpush時に追加で行った設定

追加で設定したものはありません。

> ログの内容などで原因を検索しましたか？

再度ターミナルにてheroku logsを実行しました。
```
chinatsusumikawa@MacBook-Air onigiri % heroku logs
2023-06-13T11:25:46.797474+00:00 heroku[run.3185]: State changed from starting to up
2023-06-13T11:25:51.423977+00:00 heroku[run.3185]: Process exited with status 1
2023-06-13T11:25:51.452538+00:00 heroku[run.3185]: State changed from up to complete
2023-06-13T11:26:02.789727+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=onigiri.herokuapp.com request_id=74dc6b95-d5f6-4331-be9e-1bf7c5dc6c8d fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:26:03.021850+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=onigiri.herokuapp.com request_id=b7d421f4-f78a-4a6c-b18f-78d94f559b8a fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:43:09.088632+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=onigiri.herokuapp.com request_id=5b80b734-1f60-4bce-871a-9e30c9794281 fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T11:43:09.341060+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=onigiri.herokuapp.com request_id=e7a58899-a25c-4f4c-b2ad-0191fcb46218 fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
2023-06-13T12:07:27.970863+00:00 heroku[web.1]: State changed from crashed to starting
2023-06-13T12:07:31.376572+00:00 heroku[web.1]: Starting process with command `bin/rails server -p ${PORT:-5000} -e production`
```

ログから、
```
2023-06-13T11:26:02.789727+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=onigiri.herokuapp.com request_id=74dc6b95-d5f6-4331-be9e-1bf7c5dc6c8d fwd="153.139.143.136" dyno= connect= service= status=503 bytes= protocol=https
```

を確認し、herokuのエラーコード（code=H10）を検索しました。検索した結果、アプリがクラッシュしたことが原因だと思いました。

クラッシュを改善するため、herokuの再起動：　heroku restart --app　や　heroku restart --app　onigiri
をしましたが、解消されませんでした。

恐れ入りますが、ご教授いただければと思います。

**Comment by sumikawa-40** [comment]
ご指摘ありがとうございます。
herokuでデプロイ方法の記事や動画でdatabase.yml変更をしました。
再度、heroku公式のドキュメントで確認しました。

> herokuのrailsコンソールが立ち上がる状態か確認しましたか？

herokuのrailsコンソールを実行できず、
```
chinatsusumikawa@MacBook-Air onigiri % heroku run rails console
Running rails console on ⬢ onigiri... up, run.4500 (Eco)
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract/connection_handler.rb:261:in `resolve_pool_config': database configuration does not specify adapter (ActiveRecord::AdapterNotSpecified)
        from /app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract/connection_handler.rb:129:in `establish_connection'

```
`database configuration does not specify adapter (ActiveRecord::AdapterNotSpecified)`が表示されたので、

database.ymlを初期設定に戻しました。再度、herokuへデプロイしアプリケーションエラーが解消されました。

今後は公式ドキュメントや検証を行いながら進めていきたいと思います。
ありがとうございました。
