### ISSUE TITLE
ユーザー新規登録機能をherokuへデプロイがしたい。

### ISSUE THREAD

**Issue by sumikawa-40** [sumikawa-40/onigiri#48]
### - 質問内容・実現したいこと

　ユーザー新規登録機能をherokuへデプロイがしたいです。
　また、デプロイするためには、heroku-postgresqlを使用しないと、herokuへデプロイできないのでしょうか？

### - 現状発生している問題・エラーメッセージ
　ユーザー新規登録機能とログイン・ログアウト機能を実装後、herokuへpushを行いました。
　ユーザー新規登録画面の表示と登録ができない状況です。
　 該当ブランチ #46  #47 

heroku log
```
2023-06-20T06:33:21.973707+00:00 app[web.1]: I, [2023-06-20T06:33:21.973668 #2]  INFO -- : [c69c4486-aacc-4691-a182-af07dc7c99f5] Processing by UserSessionsController#create as TURBO_STREAM
2023-06-20T06:33:21.973732+00:00 app[web.1]: I, [2023-06-20T06:33:21.973715 #2]  INFO -- : [c69c4486-aacc-4691-a182-af07dc7c99f5]   Parameters: {"authenticity_token"=>"[FILTERED]", "email"=>"sample@example.com", "password"=>"[FILTERED]", "commit"=>"ログイン"}
2023-06-20T06:33:21.975956+00:00 app[web.1]: I, [2023-06-20T06:33:21.975919 #2]  INFO -- : [c69c4486-aacc-4691-a182-af07dc7c99f5] Completed 500 Internal Server Error in 2ms (Allocations: 1608)
2023-06-20T06:33:21.976351+00:00 app[web.1]: F, [2023-06-20T06:33:21.976325 #2] FATAL -- : [c69c4486-aacc-4691-a182-af07dc7c99f5]   
2023-06-20T06:33:21.976352+00:00 app[web.1]: [c69c4486-aacc-4691-a182-af07dc7c99f5] ActiveRecord::ConnectionNotEstablished (connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
2023-06-20T06:33:21.976352+00:00 app[web.1]: 	Is the server running locally and accepting connections on that socket?
2023-06-20T06:33:21.976353+00:00 app[web.1]: ):
2023-06-20T06:33:21.976353+00:00 app[web.1]: [c69c4486-aacc-4691-a182-af07dc7c99f5]   
2023-06-20T06:33:21.976353+00:00 app[web.1]: [c69c4486-aacc-4691-a182-af07dc7c99f5] app/controllers/user_sessions_controller.rb:5:in `create'
2023-06-20T06:33:21.976915+00:00 heroku[router]: at=info method=POST path="/login" host=onigiri.herokuapp.com request_id=c69c4486-aacc-4691-a182-af07dc7c99f5 fwd="153.139.143.136" dyno=web.1 connect=0ms service=5ms status=500 bytes=1827 protocol=https
2023-06-20T07:09:23.621453+00:00 heroku[web.1]: Idling
2023-06-20T07:09:23.624889+00:00 heroku[web.1]: State changed from up to down
2023-06-20T07:09:24.451483+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2023-06-20T07:09:24.477784+00:00 app[web.1]: - Gracefully stopping, waiting for requests to finish
2023-06-20T07:09:24.478382+00:00 app[web.1]: Exiting
2023-06-20T07:09:24.618563+00:00 heroku[web.1]: Process exited with status 143
```

### - どの処理までうまく動いているのか

    ローカルホスト(http://localhost:3000/)では、新規登録・ログイン・ログアウト機能は正常に動いています。

### - 該当のソースコード

```
2023-06-20T06:33:21.976352+00:00 app[web.1]: [c69c4486-aacc-4691-a182-af07dc7c99f5] ActiveRecord::ConnectionNotEstablished (connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
2023-06-20T06:33:21.976352+00:00 app[web.1]: 	Is the server running locally and accepting connections on that socket?
2023-06-20T06:33:21.976353+00:00 app[web.1]: ):
```

### - エラーから考えられる原因

heroku logの上記をみて、マイグレーションファイルが正常でないと考えました。
1. `heroku run bundle exec rails db:migrate`を実行

```
chinatsusumikawa@MacBook-Air onigiri % heroku run bundle exec rails db:migrate
Running bundle exec rails db:migrate on ⬢ onigiri... up, run.9395 (Eco)
rails aborted!
ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:87:in `rescue in new_client'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:656:in `public_send'
途中省略
Caused by:
PG::ConnectionBad: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
/app/vendor/bundle/ruby/3.2.0/gems/pg-1.5.3/lib/pg/connection.rb:819:in `connect_start'
/app/vendor/bundle/ruby/3.2.0/gems/pg-1.5.3/lib/pg/connection.rb:819:in `connect_to_hosts'
途中省略
/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
マイグレーションファイルは作成されず。

2. `heroku run rails db:migrate:status`で状況を確認

```
chinatsusumikawa@MacBook-Air onigiri % heroku run rails db:migrate:status
Running rails db:migrate:status on ⬢ onigiri... up, run.6074 (Eco)
rails aborted!
ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:87:in `rescue in new_client'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
途中省略

Caused by:
PG::ConnectionBad: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
途中省略
(See full trace by running task with --trace)
```

状況の確認ができず。
`brew services list`でpostgresqlの状況を確認。正常に動いています。

```
chinatsusumikawa@MacBook-Air onigiri % brew services list
Name          Status  User             File
mysql         none                     
mysql@5.7     none                     
postgresql@14 started chinatsusumikawa ~/Library/LaunchAgents/homebrew.mxcl.postgresql@14.plist
```

`rails db:migrate:status`にてマイグレーションファイルの状況を確認。(正常だと思われる）
```
chinatsusumikawa@MacBook-Air onigiri % rails db:migrate:status

database: onigiri_development

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20230619050046  Sorcery core
```

databese.yml
```
# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: onigiri_development

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user running Rails.
  #username: onigiri

  # The password associated with the postgres role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: onigiri_test

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  <<: *default
  database: onigiri_production
  username: onigiri
  password: <%= ENV["ONIGIRI_DATABASE_PASSWORD"] %>

```
### - 試したこと

```
ActiveRecord::ConnectionNotEstablished (connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
2023-06-20T06:33:21.976352+00:00 app[web.1]: 	Is the server running locally and accepting connections on that socket?
```

で調べました。
該当しそうな記事
https://qiita.com/fujisawayuki/items/5ba024e5dcc04dfc009b
https://qiita.com/suzuki-x/items/b878723080aea1a673ed

がありましたが、heroku-postgresqlを使用するためなのではないかと思い、まだ実行していません。

データベースはpostgreSQLを使用しています。
デプロイするためには、heroku-postgresqlを使用しないと、herokuへデプロイはできないのでしょうか？

お忙しいところ恐れ入ります。ご教授をいただければと思います。

**Comment by kenchasonakai** [comment]
Herokuのサイトを確認した感じEcoプランにはDBは含まれていなさそうなので別でaddonが必要なのかもですね
https://jp.heroku.com/pricing#containers

**Comment by sumikawa-40** [comment]
ご対応ありがとうございます。
addonを追加し、heroku上でも新規登録・ログイン・ログアウトができました。
ありがとうございました。
